### ISSUE TITLE
Disambiguate usage of the term "test" by using "job"

### ISSUE THREAD

**Issue by ghost** [zonemaster/zonemaster-backend#1084]
With the new API (#1054) , former methods about "tests" are now called "job_*". We can now disambiguate our usage of the "test" term which refers to a lot of thing in our Zonemaster context (a testcase, a unit test, a test of a zone). Now we can refer to a job as being a task performed by the TestAgent that tests a zone.

For instance in some places `test_id` can be replaced with `job_id` in the new methods' documentation and implementation.

## Stabilization
[Tracking issue](https://github.com/zonemaster/zonemaster/issues/1175)

### Affected interfaces
Incompatibly changed:
* job_status
* job_results
* domain_history
* batch_create
* batch_status

### Dependencies
None

### Overlapping proposals
None

**Comment by mattias-p** [comment]
There are also places where we use `id`, `hash_id`, `finished_test_ids`, `test_params` and `frontend_params` for things related to jobs. These should also be taken care of at the same time.

**Comment by mattias-p** [comment]
We should limit the scope of this issue to exclude the batch methods and handle those parameters separately in order to avoid conflicts with other issues.

I suggest we rename parameter names according to this table.

|Old parameter name|New parameter name|Affected methods|
|---|---|---|
|test_id|job_id|job_status, job_params|
|id|job_id|job_params|
|frontend_params|params|domain_history|

**Comment by mattias-p** [comment]
Fixed by #1155.
