### ISSUE TITLE
Ensure that the SQLite backend can be used as a fully featured backend for Zonemaster

### ISSUE THREAD

**Issue by mtoma** [zonemaster/zonemaster-backend#179]

**Comment by matsduf** [comment]
AP1. Update the backend with randomized IDs @mtoma
AP2. Install and test on Ubuntu 14.04 @matsduf
AP3. Install and test on FreeBSD 10.3 @matsduf
AP4. Install and test on CentOS 7.1 @sandoche2k

**Comment by mtoma** [comment]
see zonemaster-gui#89

**Comment by mattias-p** [comment]
This should be solved together with #177.

**Comment by sandoche2k** [comment]
Refer to #250

**Comment by mattias-p** [comment]
I'm not sure I understand the scope of this issue. Is this about the testid values being sequence numbers? Is SQLite the only DB that uses sequence numbers? In that case the API specification should probably also be cleaned up so that it only allows the hex-string format, and of course the validation layer implementation should follow.

**Comment by matsduf** [comment]
Also see #164 about initialization of the database.

**Comment by matsduf** [comment]
Resolved by #690.
