### ISSUE TITLE
Inconsistent version information returned by "version_info" method

### ISSUE THREAD

**Issue by aabdnn** [zonemaster/zonemaster-backend#217]
The output of the "version_info" method looks inconsistent. The backend's version is reported without a "v" while the engine's version is reported with it:

```
{
  "jsonrpc": "2.0",
  "id": null,
  "result": {
    "zonemaster_backend": "1.0.7",
    "zonemaster_engine": "v1.0.15"
  }
}
```

It's quite obvious that 1.0.15 is a version number, and doesn't need a "v" before it.

**Comment by mtoma** [comment]
Do we have some kind of reference documentation for versions?

**Comment by aabdnn** [comment]
I think this is probably the canonical source on versioning numbers, and it does not recommend using a "v" in version numbers:

http://perldoc.perl.org/perlmodstyle.html#Version-numbering

**Comment by mtoma** [comment]
I then think this is more an issue for the engine repository @sandoche2k as the backend has the version numbers right.

**Comment by matsduf** [comment]
There are different recommendations. GitHub recommends using the "v". http://perldoc.perl.org/perlmodstyle.html#Version-numbering actually recommends version with two parts, not three. This would mean version "1.0007" rather than "1.0.7". We have go through versioning and document how it should be rather than doing a quick change.

**Comment by sandoche2k** [comment]
Relates to https://github.com/dotse/zonemaster/issues/465

**Comment by sandoche2k** [comment]
@mtoma close?
